liberation-fonts: Disable fontcache to avoid rootfs failure
Adding the i.MX graphics subsystems leads to a conflict
with liberation-fonts and the rootfs.

ERROR: imx-image-hovergames-ubuntu-20.04-r0 do_rootfs: Postinstall scriptlets of ['liberation-fonts'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().

Signed-off-by: Tom Hochstein <tom.hochstein@nxp.com>